repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: nested-repo-check
        name: Nested Git repo check
        entry: bash scripts/check-nested-repos.sh
        language: system
        pass_filenames: false
