name: CI

on:
  push:
    branches: [ main, phase2-dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pre-commit

      - name: Check for nested repos
        run: bash scripts/check-nested-repos.sh

      - name: Run pre-commit (all files)
        run: pre-commit run --all-files --show-diff-on-failure -c .pre-commit-config.yaml

      - name: Run pytest
        run: pytest -q tests --ignore=whisper