name: CI

on:
  push:
    branches: [ main, phase2-dev ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '17 8 * * *'  # daily at 08:17 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/src
    steps:
      - uses: actions/checkout@v4

      - name: Nested repo check
        shell: bash
        run: |
          chmod +x scripts/check-nested-repos.sh
          bash scripts/check-nested-repos.sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run pytest
        run: pytest -q tests --ignore=whisper